/*
 * File: app/view/Main.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Afc.view.Main', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.main',
    requires: [
        'Afc.view.Nav',
        'Afc.view.TweetSearch',
        'Afc.view.TweetList'
    ],

    config: {
        items: [
            {
                xtype: 'mainnav',
                title: 'グループ',
                iconCls: 'home'
            },
            {
                xtype: 'container',
                layout: {
                    type: 'fit'
                },
                title: 'Twitter',
                iconCls: 'info',
                items: [
                    {
                        xtype: 'tweetsearch'
                    },
                    {
                        xtype: 'tweetlist'
                    }
                ]
            }
        ],
        tabBar: {
            docked: 'bottom'
        }
    }

});