/*
 * File: app/controller/Groups.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Afc.controller.Groups', {
    extend: 'Ext.app.Controller',
    config: {
        refs: {
            grouplist: 'grouplist',
            nav: 'mainnav',
            search: 'searchfield',
            tweetslist: 'tweetslist',
            reload: 'button[action=reload]'
        },

        control: {
            "grouplist": {
                itemtap: 'onGroupSelected'
            },
            "search": {
                action: 'onTweetSearch'
            },
            "reload": {
                tap: 'onReload'
            }
        }
    },

    onGroupSelected: function(l, i, t, rec) {
        this.getNav().push({
            xtype: 'tabpanel',
            title: rec.get('group'),
            items: [{
                xtype: 'countrylist',
                title: '国',
                store: rec.countries()
            },{
                xtype: 'matchlist',
                title: '日程',
                store: rec.matches()
            }]
        });

    },

    onTweetSearch: function(target) {
        var q = this.getSearch().getValue(),
            s = Ext.getStore('Tweets');

        s.load({
            params: { q: q}
        });
    },

    onReload: function(target) {
        this.onTweetSearch();
        /*

        Ext.device.Notification.show({
        title: 'Verification',
        message: 'Is your email address is: test@sencha.com',
        buttons: Ext.MessageBox.OKCANCEL,
        callback: function(button) {
        if (button == "ok") {
        console.log('Verified');
        } else {
        console.log('Nope.');
        }
        }
        });
        */
    }

});